// Generated by @measured/calibrate-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import {
  buildClbrDivider,
  type ClbrDividerProps,
} from "@measured/calibrate-core";
import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type DividerProps = ClbrDividerProps & NativeAttrsFor<HTMLElement>;

export function Divider(props: DividerProps): ReturnType<typeof reactify> {
  return reactify(
    buildClbrDivider(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
