// Generated by @measured/calibrate-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import {
  buildClbrSurface,
  type ClbrSurfaceProps,
} from "@measured/calibrate-core";
import type { ReactNode } from "react";
import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_SURFACE_CHILDREN = "__CLBR_SLOT_SURFACE_CHILDREN__";

export type SurfaceProps = Omit<ClbrSurfaceProps, "children"> & {
  children: ReactNode;
} & NativeAttrsFor<HTMLDivElement>;

export function Surface(props: SurfaceProps): ReturnType<typeof reactify> {
  const { children, variant, ...rest } = props;
  const node = buildClbrSurface({
    children: SLOT_SURFACE_CHILDREN,
    variant,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      [SLOT_SURFACE_CHILDREN]: children,
    },
  );
}
