// Generated by @measured/calibrate-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildClbrCard, type ClbrCardProps } from "@measured/calibrate-core";
import type { ReactNode } from "react";
import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_CARD_DESCRIPTION = "__CLBR_SLOT_CARD_DESCRIPTION__";
const SLOT_CARD_NOTE = "__CLBR_SLOT_CARD_NOTE__";

export type CardProps = Omit<ClbrCardProps, "description" | "note"> & {
  description: ReactNode;
  note?: ReactNode;
} & NativeAttrsFor<HTMLDivElement>;

export function Card(props: CardProps): ReturnType<typeof reactify> {
  const { description, headingLevel, href, note, surface, title, ...rest } =
    props;
  const hasNote = note != null && note !== false;
  const node = buildClbrCard({
    description: SLOT_CARD_DESCRIPTION,
    headingLevel,
    href,
    note: hasNote ? SLOT_CARD_NOTE : undefined,
    surface,
    title,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      [SLOT_CARD_DESCRIPTION]: description,
      ...(hasNote ? { [SLOT_CARD_NOTE]: note } : {}),
    },
  );
}
