// Generated by @measured/calibrate-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import {
  buildClbrPoster,
  type ClbrPosterProps,
} from "@measured/calibrate-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_POSTER_MEDIA = "__CLBR_SLOT_POSTER_MEDIA__";
const SLOT_POSTER_CHILDREN = "__CLBR_SLOT_POSTER_CHILDREN__";

export type PosterProps = Omit<ClbrPosterProps, "media" | "children"> & {
  media: ReactNode;
  children?: ReactNode;
} & NativeAttrsFor<HTMLDivElement>;

export function Poster(props: PosterProps): ReturnType<typeof reactify> {
  const { children, contentTheme, id, media, surface, ...rest } = props;
  const hasChildren = children != null && children !== false;
  const node = buildClbrPoster({
    children: hasChildren
      ? (SLOT_POSTER_CHILDREN as unknown as ClbrPosterProps["children"])
      : undefined,
    contentTheme,
    id,
    media: SLOT_POSTER_MEDIA as unknown as ClbrPosterProps["media"],
    surface,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      [SLOT_POSTER_MEDIA]: media,
      ...(hasChildren ? { [SLOT_POSTER_CHILDREN]: children } : {}),
    },
  );
}
