// Generated by @measured/calibrate-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import {
  buildClbrAlert,
  CLBR_ALERT_EVENT_BEFORE_DISMISS,
  CLBR_ALERT_EVENT_DISMISS,
  type ClbrAlertProps,
  defineClbrAlert,
} from "@measured/calibrate-core";
import {
  type Ref,
  type RefCallback,
  useCallback,
  useEffect,
  useRef,
} from "react";
import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

function assignRef<T>(ref: Ref<T> | undefined, value: T | null): void {
  if (typeof ref === "function") ref(value);
  else if (ref) (ref as { current: T | null }).current = value;
}

export type AlertBeforeDismissHandler = (event: Event) => void;

export type AlertDismissHandler = (event: Event) => void;

export type AlertProps = ClbrAlertProps &
  NativeAttrsFor<HTMLElement> & {
    onBeforeDismiss?: AlertBeforeDismissHandler;
    onDismiss?: AlertDismissHandler;
  };

export function Alert(props: AlertProps): ReturnType<typeof reactify> {
  const { onBeforeDismiss, onDismiss, ref: callerRef, ...rest } = props;
  useEffect(() => {
    defineClbrAlert();
  }, []);
  const elRef = useRef<HTMLElement | null>(null);
  useEffect(() => {
    const el = elRef.current;
    if (!el || !onBeforeDismiss) return;
    el.addEventListener(
      CLBR_ALERT_EVENT_BEFORE_DISMISS,
      onBeforeDismiss as EventListener,
    );
    return () =>
      el.removeEventListener(
        CLBR_ALERT_EVENT_BEFORE_DISMISS,
        onBeforeDismiss as EventListener,
      );
  }, [onBeforeDismiss]);
  useEffect(() => {
    const el = elRef.current;
    if (!el || !onDismiss) return;
    el.addEventListener(CLBR_ALERT_EVENT_DISMISS, onDismiss as EventListener);
    return () =>
      el.removeEventListener(
        CLBR_ALERT_EVENT_DISMISS,
        onDismiss as EventListener,
      );
  }, [onDismiss]);
  const mergedRef = useCallback<RefCallback<HTMLElement>>(
    (node) => {
      elRef.current = node;
      assignRef(callerRef, node);
    },
    [callerRef],
  );
  return reactify(buildClbrAlert(props), {
    ...pickNativeExtras(rest as unknown as Record<string, unknown>),
    ref: mergedRef,
  });
}
