// Generated by @measured/calibrate-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildClbrIcon, type ClbrIconProps } from "@measured/calibrate-core";
import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type IconProps = ClbrIconProps & NativeAttrsFor<SVGSVGElement>;

export function Icon(props: IconProps): ReturnType<typeof reactify> {
  return reactify(
    buildClbrIcon(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
