// Generated by @measured/calibrate-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import {
  buildClbrRange,
  type ClbrRangeProps,
  defineClbrRange,
} from "@measured/calibrate-core";
import { useEffect } from "react";
import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type RangeProps = ClbrRangeProps & NativeAttrsFor<HTMLElement>;

export function Range(props: RangeProps): ReturnType<typeof reactify> {
  useEffect(() => {
    defineClbrRange();
  }, []);
  return reactify(
    buildClbrRange(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
