// Generated by @measured/calibrate-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import {
  buildClbrPattern,
  type ClbrPatternProps,
} from "@measured/calibrate-core";
import type { ReactNode } from "react";
import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_PATTERN_CHILDREN = "__CLBR_SLOT_PATTERN_CHILDREN__";

export type PatternProps = Omit<ClbrPatternProps, "children"> & {
  children?: ReactNode;
} & NativeAttrsFor<HTMLDivElement>;

export function Pattern(props: PatternProps): ReturnType<typeof reactify> {
  const { children, tone, size, variant, ...rest } = props;
  const hasChildren = children != null && children !== false;
  const node = buildClbrPattern({
    children: hasChildren ? SLOT_PATTERN_CHILDREN : undefined,
    tone,
    size,
    variant,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      ...(hasChildren ? { [SLOT_PATTERN_CHILDREN]: children } : {}),
    },
  );
}
